[package]
name = "game-minter-meta"
version = "0.0.0"
authors = [ "Krogan",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.game-minter]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.5"