// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    game_balancer
    (
        registerProposalType
        registerUser
        swapUser
        removeUser
        changeSigner
        getFactions
        getUserFaction
    )
}

elrond_wasm_node::wasm_empty_callback! {}
