[package]
name = "game-balancer-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.game-balancer]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.37.0"
